config/routes.rb
Scarb::Application.routes.draw do

root :to => 'items#list'

match '/about' => 'application#about'

match 'basket/:id/add' => 'basket#add_item', :via=> [:get,:put], :as => :basket_add
match 'basket/:id/list' => 'basket#list', :via=> :get, :as => :basket_list
match 'basket/:id/delete' => 'basket#delete', :via=> :get, :as => :basket_delete

match 'inbox/:id/incoming' => 'inbox#incoming_list', :via=> :get, :as => :incoming_list
match 'inbox/:id/sent' => 'inbox#sent_list', :via=> :get, :as => :sent_list
match 'inbox/:id/notify' => 'inbox#notify_owner', :via=> :get, :as => :inbox_notify
match 'inbox/:id/reply' => 'inbox#reply', :via=> [:get,:post], :as => :inbox_reply
match 'inbox/:id/delete' => 'inbox#delete', :via=> :get, :as => :inbox_delete

match '/signup' => 'user#new'
match '/signin' => 'sessions#new', :via => [:get,:post], :as => :sessions_new
match '/signout' => 'sessions#destroy', :as => :sessions_out

match 'items' => 'items#list', :via=> :get, :as => :items_list
match 'items/create' => 'items#create', :via=> :post, :as => :items_create
match 'items/:id/update' => 'items#update', :via=> :put, :as => :items_update
match 'items/new' => 'items#new', :via=> [:get,:put], :as => :items_new
match 'items/:id' => 'items#show', :via=> :get, :as => :items
match 'items/:id/edit' => 'items#edit', :via=> [:get,:put], :as => :items_edit
match 'items/:id/delete' => 'items#delete', :via=> :get, :as => :items_delete

match 'user' => 'user#list', :via=> :get, :as => :user_list
match 'user/:id' => 'user#show', :via=> :get, :as => :user
match 'user/new' => 'user#new', :via=> :get, :as => :user_new
match 'user/create' => 'user#create', :via=> :post, :as => :user_create
match 'user/:id/edit' => 'user#edit', :via=> [:get,:put], :as => :user_edit
match 'user/:id/delete' => 'user#delete', :via=> :get, :as => :user_delete
match 'user/:id/items' => 'user#my_items', :via=> :get, :as => :user_items

get "user/update"

match 'category/:id' => 'category#show', :via=> :get, :as => :category
match 'category' => 'category#list', :via=> :get, :as => :category_list
 
  get "category/new"
 post "category/create"
  get "category/edit"
  get "category/update"
  get "category/delete"

end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
 before_filter :require_login

    def add_item
	if !current_user.basket_items.create(:item_id => params[:id], :status => ITEM_NEW)
	    flash[:error] = t(:basket_error)
	end
	redirect_to request.referer
    end

    def list
	if is_admin? || params[:id] == current_user.id
	 basket = User.find(params[:id]).basket_items
	else
	 basket = User.find(current_user.id).basket_items
	end
	@user_basket = Kaminari.paginate_array(basket).page(params[:page]).per(10)
    end

    def delete
	@basket_item = current_user.basket_items.find_by_id(params[:id])
	if !@basket_item.nil?
         @basket_item.destroy
	end
     redirect_to :action => 'list', :id => current_user.id
    end
end

app/helpers/basket_helper.rb
module BasketHelper

    def inbasket_count
	BasketItem.where(:user_id => session[:user_id], :status => ITEM_NEW).count
    end

end

app/views/basket/list.html.erb
<% if @user_basket.blank? %>
<div class="message notice"><p class="m8 c00"><%= t(:empty) %></p></div>
<% else %>
<% @user_basket.each do |i| %>
<% c_item = Item.find_by_id(i.item_id) %>
<% if c_item.nil? %>
    <% i.destroy %>
<% else %>

<div class="list_box">
<div class="list_box_left">
<%= link_to(image_tag(c_item.item_photos.first.photo.url(:small)), items_path(c_item.id)) %>
</div>

<div class="list_box_right">
<span class="db c00 pb"><%= c_item.item_action.item_act %></span>
<span class="db pb button fr fb"><%= link_to t("Remove"), basket_delete_path(i.id), :configrm => "Sure?" %></span>
<% if i.status == ITEM_NEW %>
<span class="db button fr fb"><%= link_to t("NotifyOwner"), inbox_notify_path(c_item.id) %></span>
<% else %>
<br><br>
<span class="c00 fb fr cred"><%= t("waiting")%></span>
<% end %>
</div>

<div class="list_box_middle">
<h3><%= link_to c_item.item_name, items_path(c_item.id) %></h3>
<span class="db pb"><%= c_item.item_desc[0..80].concat("...") %></span>
<span class="db pb"><%= image_tag("/assets/icons/cost.png")%> <%= link_to Category.find(c_item.category_id).category_name, category_path(c_item.category_id) %></span>
<span class="db f10"><%= image_tag("/assets/icons/user.png")%> <%= User.find_by_id(c_item.user_id).user_name %></span>
<span class="c00 db f10"><%= c_item.created_at %></span>
</div>

</div>
<% end %>

<% end %>
<%= paginate @user_basket %>
<% end %>