config/routes.rb
Scarb::Application.routes.draw do

root :to => 'items#list'

match '/about' => 'application#about'

match 'basket/:id/add' => 'basket#add_item', :via=> [:get,:put], :as => :basket_add
match 'basket/:id/list' => 'basket#list', :via=> :get, :as => :basket_list
match 'basket/:id/delete' => 'basket#delete', :via=> :get, :as => :basket_delete

match 'inbox/:id/incoming' => 'inbox#incoming_list', :via=> :get, :as => :incoming_list
match 'inbox/:id/sent' => 'inbox#sent_list', :via=> :get, :as => :sent_list
match 'inbox/:id/notify' => 'inbox#notify_owner', :via=> :get, :as => :inbox_notify
match 'inbox/:id/reply' => 'inbox#reply', :via=> [:get,:post], :as => :inbox_reply
match 'inbox/:id/delete' => 'inbox#delete', :via=> :get, :as => :inbox_delete

match '/signup' => 'user#new'
match '/signin' => 'sessions#new', :via => [:get,:post], :as => :sessions_new
match '/signout' => 'sessions#destroy', :as => :sessions_out

match 'items' => 'items#list', :via=> :get, :as => :items_list
match 'items/create' => 'items#create', :via=> :post, :as => :items_create
match 'items/:id/update' => 'items#update', :via=> :put, :as => :items_update
match 'items/new' => 'items#new', :via=> [:get,:put], :as => :items_new
match 'items/:id' => 'items#show', :via=> :get, :as => :items
match 'items/:id/edit' => 'items#edit', :via=> [:get,:put], :as => :items_edit
match 'items/:id/delete' => 'items#delete', :via=> :get, :as => :items_delete

match 'user' => 'user#list', :via=> :get, :as => :user_list
match 'user/:id' => 'user#show', :via=> :get, :as => :user
match 'user/new' => 'user#new', :via=> :get, :as => :user_new
match 'user/create' => 'user#create', :via=> :post, :as => :user_create
match 'user/:id/edit' => 'user#edit', :via=> [:get,:put], :as => :user_edit
match 'user/:id/delete' => 'user#delete', :via=> :get, :as => :user_delete
match 'user/:id/items' => 'user#my_items', :via=> :get, :as => :user_items

get "user/update"

match 'category/:id' => 'category#show', :via=> :get, :as => :category
match 'category' => 'category#list', :via=> :get, :as => :category_list
 
  get "category/new"
 post "category/create"
  get "category/edit"
  get "category/update"
  get "category/delete"

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
    # generate password accessor
    apply_simple_captcha
    
    attr_accessor :password
    
    attr_accessible :captcha, :captcha_key, :password, :password_confirmation, :photo, :user_name, :user_password, :user_email, :user_city, :user_phone, :user_show_personal, :user_attr

    has_many :basket_items, :dependent => :destroy	# user's basket 
    has_many :inbox_messages, :dependent => :destroy	#  inbox: incomind/sent messages
    has_many :items, :dependent => :destroy		# user items
    has_many :comments, :dependent => :destroy

    accepts_nested_attributes_for :inbox_messages, :basket_items, :items, :comments
    
    has_attached_file :photo, :styles => { :small => "150x180>", :large => "250x280>" }
    validates_attachment_size :photo, :less_than => 1.megabytes
    
    validates :user_name, :length => { :maximum => 32, :minimum => 4 },
	      :uniqueness => { :case_sensitive => false }
    validates :user_email,
	      :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i },
	      :uniqueness => { :case_sensitive => false }
    validates :password, :confirmation => true, :length => { :within => 6..40 }

    before_save :encrypt_password
    
    def city
	City.find_by_id(self.user_city).city_name
    end
    
    def has_password?(submitted_password)
     self.user_password == encrypt(submitted_password)
    end
    
    def self.authenticate(email, submitted_password)
	user = find_by_user_email(email)
        return nil  if user.nil?
        return user if user.has_password?(submitted_password)
    end          

    
private

    def encrypt_password
	self.salt = make_salt if new_record?
	self.user_password = encrypt(self.password)
    end
              
    def make_salt
        secure_hash("#{Time.now.utc}--#{password}")
    end
                        
    def secure_hash(string)
        Digest::SHA2.hexdigest(string)
    end
                                      
    def encrypt(string)
	secure_hash("#{salt}--#{string}")
    end
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController
 before_filter :require_login, :only => [:show, :list, :my_items, :edit, :delete]
 
def list
	@title = t(:users)
        @users = User.find(:all)
end

def my_items
	@title = t(:my_items)
        @items = Item.where("user_id=?", params[:id] ).order('created_at').page(params[:page]).per(10)
#        @items = User.find(params[:id]).items.find_all.order('created_at').page(params[:page]).per(10)
end

def edit
    @title = t(:profile_edit)
    if request.put?
      @user = User.find(params[:id])
	if @user.update_attributes(params[:user])
	redirect_to :action => 'show', :id => @user
	    else
    	    flash.now[:error] = "Can't update user attributes!"
	end
    else
    	if is_admin?
	  @user = User.find(params[:id])
	else
	  @user = User.find(session[:user_id])
	end
    end
end

    def update
    end

     
  def show
    @user = User.find(params[:id])
    @title = @user.user_name
  end

  def new
    @user = User.new
  end

 def delete
    @user = User.find(params[:id])
    if @user.destroy
    	redirect_to :action => 'list'
    else
	redirect_to :action => 'delete'
    end
 end
   
  def create
    @user = User.new(params[:user])
#    @user.save_with_captcha
    if @user.save_with_captcha
	flash[:success] = t(:welcome)

	UserMailer.welcome_email(@user).deliver
	sign_in(@user)
	redirect_to @user

    else
	flash[:error] = t(:user_error)
	render :action => 'new'
     end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_test.html.erb
<div>
<%= image_tag @user.photo.url %>
</div>

app/views/user/edit.html.erb
<div class="block bw1">
<h2><%= t("edit_profile")%></h2>
<div class="block_content">
<%= form_for @user, :url => user_edit_path(@user), :html => {:multipart => true} do |f| %>

<%= errors_for(@user, t("error")).html_safe %>

<table>
<tbody>

<tr>
<td class="eformCln1 c00"><%= f.label t("name") %>:</td>
<td class="eformCln2"><%= f.text_field :user_name %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label "E-Mail" %>:</td>
<td class="eformCln2"><%= f.text_field :user_email %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("password") %>:</td>
<td class="eformCln2"><%= f.password_field :password %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("confirmation") %>:</td>
<td class="eformCln2"><%= f.password_field :password_confirmation %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("phone") %>:</td>
<td class="eformCln2"><%= f.text_field :user_phone %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("city") %>:</td>
<td class="eformCln2"><%= collection_select :user, :user_city, City.find(:all), :id, :city_name %></td>
</tr>


<tr>
<td><br></td>
<td> </td>
</tr>

<tr>
<td class ="eformCln1"></td>
<td class="eformCln2"><%= image_tag @user.photo.url(:small), :style => "border: solid 1px;" %></td>
</tr>

<tr>
<td class ="eformCln1"></td>


<td class="eformCln2">

<div class="fm-item">
<%= f.file_field :photo,:id => "upload-file" %>
</div>

<div style="width: 50em;">
<button type="submit" id="upload-button">Submit</button>
<span id="file-name"></span>
</div>
</td>
</tr>

<tr>
<td class ="eformCln1"></td>
<td class="eformCln2 c00"><%= f.check_box :user_show_personal %><%= t("personal")%></td>
</tr>

<tr>
<td class ="eformCln1">
</td>
<td class="eformCln2" style="padding-top: 10px;"><%= f.submit t("save") %></td>
</tr>

</tbody>
</table>

<% end %>
</div>
</div>

<%= link_to t('back'), request.referer %>

app/views/user/list.html.erb
<% if @users.blank? %>
<div class="message notice"><p class="m8"><%= t(:empty) %></p></div>
<% else %>
<ul id="users">
<% @users.each do |u| %>
<li>

<%= link_to u.user_name, user_path(u.id) %>

<% if is_admin? %>
<b><%= link_to 'Edit', user_edit_path(u.id) %></b>
<b><%= link_to 'Delete', user_delete_path(u.id), :confirm => "Sure?"  %></b>
<% end %>

</li>
<% end %>
</ul>
<% end %>

<% if is_admin? %>
<p><%= link_to "Add new", {:action => 'new' }%></p>
<% end %>

app/views/user/my_items.html.erb
<% if @items.blank? %>
<div class="message notice"><p class="m8"><%= t(:empty) %></p></div>
<% else %>

<% @items.each do |i| %>

<div class="list_box">
<div class="list_box_left">
<%= link_to(image_tag(i.item_photos.first.photo.url(:small)), items_path(i.id)) unless i.item_photos.first.nil? %>
</div>

<div class="list_box_right">
<span class="f10 fb"><%= link_to t(:edit), items_edit_path(i.id) %></span>
 <span class="f10 fb"><%= link_to t(:delete), items_delete_path(i.id), :confirm => "Sure?"  %></span>
<span class="act01 db c00 pb"><%= i.item_action.item_act %></span>
</div>

<div class="list_box_middle">
<h3><%= i.item_name %></h3>
<span class="db pb"><%= i.item_desc[0..80].concat("...") %></span>
<span class="db pb"><% Category.find(i.category_id).category_name %></span>
<span class="c00 db f10"><%= i.created_at %></span>
</div>

</div>
<% end %>
<% end %>
<%= paginate @items  %>
<p><%= link_to t("add"), items_new_path, :class => 'button' %></p>

app/views/user/new.html.erb
<div class="block">
<h2><%= t(:register) %></h2>
<div class="block_content">
<%= form_for @user, :url => user_create_path do |f| %>

<%= errors_for(@user, t(:user_error)).html_safe %>

<table>
<tbody>

<tr>
<td class="eformCln1 c00"><%= f.label t(:name) %></td>
<td class="eformCln2"><%= f.text_field :user_name %><span class="cred fb"> *</span></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label "e-mail" %></td>
<td class="eformCln2"><%= f.text_field :user_email %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t(:password) %></td>
<td class="eformCln2"><%= f.password_field :password %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t(:confirmation) %></td>
<td class="eformCln2"><%= f.password_field :password_confirmation %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t(:phone) %></td>
<td class="eformCln2"><%= f.text_field :user_phone %></td>
<tr>

<tr>
<td class="eformCln1 c00"><%= f.label t(:city) %></td>
<td class="eformCln2"><%= collection_select :user, :user_city, City.find(:all), :id, :city_name %></td>
</tr>

<tr>
<td class="eformCln1"> </td>
<td class="eformCln2 pb10"><%= show_simple_captcha(:object=>"user") %></td>
</tr>
<tr>
<td class="eformCln1"> </td>
<td class="eformCln2"><%= f.submit t(:create) %></td>
</tr>

</tbody>
</table>

<% end %>
</div>
</div>

app/views/user/show.html.erb
<h1><%= @user.user_name %></h1>
<div class="list_box">
<div id="divUserPhoto">
<div align="center" id="divUserPic">
<% if @user.photo.exists? %>
<%= image_tag @user.photo.url(:small) %>
<% else %>
<%= image_tag "/assets/photo.jpg" %>
<% end %>
</div>
</div>

<div class="list_box_middle lp10">
<span class="fr"><%= link_to t("edit"), user_edit_path(current_user.id),:class => "button c00" %></span>

<table>
<tbody>

<tr>
<td class="fb c00 fr"><%= t("name") %>: </td>
<td class=""><%= @user.user_name %></td>
</tr>

<tr>
<td class="fb c00 fr"><%= t("city")%>:</td> 
<td><%= @user.city %></td>
</tr>

<% if @user.user_show_personal || is_admin? %>
<tr>
<td class="fb c00 fr">E-mail:</td> 
<td><%= @user.user_email %></td>
</tr>
<tr>
<td class="fb c00 fr"><%= t("phone")%>:</td> 
<td><%= @user.user_phone %></td>
</tr>
<% end %>
<tr>
<td class="fb c00 fr"><%= t("created")%>:</td> 
<td><%= @user.created_at %></td>
</tr>
</tbody>
</table>

</div>
</div>
<%= link_to t("back"), request.referer %>