config/routes.rb
Scarb::Application.routes.draw do

root :to => 'items#list'

match '/about' => 'application#about'

match 'basket/:id/add' => 'basket#add_item', :via=> [:get,:put], :as => :basket_add
match 'basket/:id/list' => 'basket#list', :via=> :get, :as => :basket_list
match 'basket/:id/delete' => 'basket#delete', :via=> :get, :as => :basket_delete

match 'inbox/:id/incoming' => 'inbox#incoming_list', :via=> :get, :as => :incoming_list
match 'inbox/:id/sent' => 'inbox#sent_list', :via=> :get, :as => :sent_list
match 'inbox/:id/notify' => 'inbox#notify_owner', :via=> :get, :as => :inbox_notify
match 'inbox/:id/reply' => 'inbox#reply', :via=> [:get,:post], :as => :inbox_reply
match 'inbox/:id/delete' => 'inbox#delete', :via=> :get, :as => :inbox_delete

match '/signup' => 'user#new'
match '/signin' => 'sessions#new', :via => [:get,:post], :as => :sessions_new
match '/signout' => 'sessions#destroy', :as => :sessions_out

match 'items' => 'items#list', :via=> :get, :as => :items_list
match 'items/create' => 'items#create', :via=> :post, :as => :items_create
match 'items/:id/update' => 'items#update', :via=> :put, :as => :items_update
match 'items/new' => 'items#new', :via=> [:get,:put], :as => :items_new
match 'items/:id' => 'items#show', :via=> :get, :as => :items
match 'items/:id/edit' => 'items#edit', :via=> [:get,:put], :as => :items_edit
match 'items/:id/delete' => 'items#delete', :via=> :get, :as => :items_delete

match 'user' => 'user#list', :via=> :get, :as => :user_list
match 'user/:id' => 'user#show', :via=> :get, :as => :user
match 'user/new' => 'user#new', :via=> :get, :as => :user_new
match 'user/create' => 'user#create', :via=> :post, :as => :user_create
match 'user/:id/edit' => 'user#edit', :via=> [:get,:put], :as => :user_edit
match 'user/:id/delete' => 'user#delete', :via=> :get, :as => :user_delete
match 'user/:id/items' => 'user#my_items', :via=> :get, :as => :user_items

get "user/update"

match 'category/:id' => 'category#show', :via=> :get, :as => :category
match 'category' => 'category#list', :via=> :get, :as => :category_list
 
  get "category/new"
 post "category/create"
  get "category/edit"
  get "category/update"
  get "category/delete"

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :category
    belongs_to :item_action
    belongs_to :user

    has_many :item_photos, :dependent => :destroy
    has_many :comments, :dependent => :destroy

    accepts_nested_attributes_for :comments, :item_photos, :allow_destroy => true

    validates :item_name, :presence => true, :length => { :maximum => 128, :minimum => 3 }
    validates :item_desc, :presence => true, :length => { :maximum => 1024, :minimum => 20 }

    attr_accessible :category_id, :item_action_id, :item_name, :item_desc, :item_action, :item_attr, :item_photos, :item_photos_attributes
end

app/models/item_action.rb
class ItemAction < ActiveRecord::Base
    has_many :items
    attr_accessible :item_act
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 before_filter :require_login, :only => [:new, :edit, :delete, :create, :update]
  
  def new
    @item = Item.new
    3.times {@item.item_photos.build}
  end

# edit item
  def edit

    if request.put?
     @item = Item.find(params[:id])
    if is_admin? || @item.user_id == current_user.id

	if !params[:pix_destroy].blank?
	     params[:pix_destroy].each { |pix|
    		@item.item_photos[pix.to_i].delete
	    }
        end
	    if @item.update_attributes(params[:item])
	    redirect_to :controller => 'user', :action => 'my_items', :id => current_user
		else
    		flash.now[:error] = "Can't update item!"
	    end
     else
     flash[:error] = "It is not your item!"
     redirect_to :action=>'list'
     end

    else

     @item = Item.find_by_id(params[:id])
     if is_admin? || @item.user_id == current_user.id
     for pix in (0..2)
      @item.item_photos.build if @item.item_photos[pix].blank? 
     end
     else
     flash[:error] = "It is not your item!"
     redirect_to :action=>'list'
     end

    end
  end

# list items 
  def list
	where_str = ""
	tmp_cid = params[:category]
	if !tmp_cid.blank?
	    where_str = "category_id = #{tmp_cid}"
	end
	tmp_aid = params[:iaction]
	if !tmp_aid.blank?
	    if where_str.blank?
	    where_str += "item_action_id = #{tmp_aid}"
	    else
	    where_str += " AND item_action_id = #{tmp_aid}"
	    end
	end
	case params[:sort]
	    when "0"
		order_str = "created_at DESC"
	    when "1"
		order_str = "item_name"
	    when "2"
		order_str = "user_id"
	    when "3"
		@items = Item.joins(:user).order("user_city").page(params[:page]).per(2)
		return
	    else
		order_str = "created_at DESC"
	    end
        @items = Item.where(where_str).order(order_str).page(params[:page]).per(2)
  end

 def delete
    @item = Item.find_by_id(params[:id])
    if is_admin? || @item.user_id == current_user.id
    if @item.destroy
    	redirect_to :action => 'list'
    else
	redirect_to :action => 'delete'
    end
    else
    flash[:error] = "It is not your item!"
    redirect_to :action=>'list'
    end
 end

def show
    @title = "Show Item"
    @item = Item.find(params[:id])
    @category = Category.find(@item.category_id)
    @action = ItemAction.find(@item.item_action_id)
    @user = User.find(@item.user_id)
end


  def create
#    @name = params[:user]
#    render(:text => "Hey - Rails is cool! #{@name['user_name']}")

        @item = Item.new(params[:item])
        @item.user_id = current_user.id		# future: check err
	if @item.save
		redirect_to :action => 'list'
	else
            3.times {@item.item_photos.build} if @item.item_photos.blank?
	    render :action => 'new'
        end
  end

 def update
 end

end

app/helpers/item_helper.rb
module ItemHelper

 def latest_items
     Item.order("created_at DESC").limit(3)
 end

end

app/views/items/_admin_edit.html.erb
<% if is_admin? %>
<span class="f10 fb"><%= link_to t(:edit), items_edit_path(item.id) %></span> .
<span class="f10 fb"><%= link_to t(:delete), items_delete_path(item.id), :confirm => "Sure?"  %></span>
<% end %>

app/views/items/_item.html.erb
<p><%= item.item_name %></p>

app/views/items/_sort_bar.html.erb
<div class="page-wrap">
<div style="margin-bottom:5px;">
<%= form_tag({:action => 'list'}, :method => "get") do %>
    <label for="f"><%= t(:filter)%></label>:
    <%= select_tag "category", options_for_select(Category.all.collect {|c| [ c.category_name, c.id ] }), {:include_blank => true} %>
    <%= select_tag "iaction", options_for_select(ItemAction.all.collect {|a| [ a.item_act, a.id ] }), {:include_blank => true} %>
    <label for="sort"><%=t(:sort)%></label>:
    <%= select_tag "sort", options_for_select({ "Дата" => "0", "Название" => "1", "Владелец" => "2", "Город" => "3" }) %>
    <%= submit_tag t(:search), :class => "fr"  %>
    <% end %>
</div>
</div>

app/views/items/edit.html.erb
<div class="block">
<h2><%= t("edit")%></h2>
<div class="block_content">

<%= form_for @item, :url => items_edit_path(@item), :html => {:multipart => true} do |f| %>

<%= errors_for(@item, t("error")).html_safe %>

<table>
<tbody>

<tr>
<td class="eformCln1 c00"><%= f.label t("item_name") %></td>
<td class="eformCln2"><%= f.text_field :item_name %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("description") %></td>
<td class="eformCln2"><%= f.text_area :item_desc, :size => "60x12" %></td>
</tr>
<tr>
<td class="eformCln1 c00"> </td>
<td class="eformCln2"><%= collection_select :item, :category_id, Category.find(:all), :id, :category_name %>
<%= collection_select :item, :item_action_id, ItemAction.find(:all), :id, :item_act %></td>
</tr>

<% x=0 %>
<%= f.fields_for :item_photos do |builder|  %>
<tr>
<td class="eformCln1"> </td>
<td class="eformCln2">
<%= image_tag @item.item_photos[x].photo.url(:small) %> 
    <% unless @item.item_photos[x].new_record? %>
	<br>
	<%= check_box_tag 'pix_destroy[]',x %>
	<%= f.label '_destroy', t(:delete) %>
    <% else %>
    <br>
    <div class="fm-item">
    <%= builder.file_field :photo,:id => "upload-file#{x}" %>
    </div>
    <div style="width: 50em;">
    <button type="submit" id="upload-button<%= x %>">Submit</button>
    <span id="file-name<%= x %>"></span>
    </div>
    <% end %>
<% x+=1 %>
</td>
</tr>
<% end %>

<tr>
<td class="eformCln1"> </td>
<td class="eformCln2"><%= f.submit t('update') %></td>
</tr>

</tbody>
</table>

<% end %>
</div>
</div>

<%= link_to t('back'), request.referer %>

app/views/items/list.html.erb
<%= render "sort_bar" %>
<% if @items.blank? %>
<div class="message notice"><p class="m8"><%= t(:empty) %></p></div>
<% else %>
<% @items.each do |i| %>
<div class="list_box">
<div class="list_box_left">
<%= link_to(image_tag(i.item_photos.first.photo.url(:small)), i.item_photos.first.photo.url(:large), :rel => "lightbox") unless i.item_photos.first.nil? %>
</div>

<div class="list_box_right">

<%= render :partial => "admin_edit", :locals => { :item => i } %>

<span class="act01 db c00"><%= i.item_action.item_act %></span>
<span class="db pb"><%= User.find_by_id(i.user_id).city %></span>

<% if signed_in? %>
    <% if i.user_id != current_user.id %>
	<% if current_user.basket_items.find_by_item_id(i.id) %>
	    <span class="db pb fb cred"><%= t(:in_basket)%></span>
	<% else %>
	    <span class="fr"><%= link_to t(:get), basket_add_path(i.id),:class => "button c00" %></span>
	<% end %>
    <% end %>
<% end %>
</div>

<div class="list_box_middle">
<h3><%= link_to i.item_name, items_path(i.id) %></h3>
<span class="db pb"><%= i.item_desc[0..80].concat("...") %></span>
<span class="db "><%= image_tag("/assets/icons/cost.png")%> <%= link_to Category.find(i.category_id).category_name, category_path(i.category_id) %></span>
<span class="db f10"><%= image_tag("/assets/icons/user.png")%> <%= User.find_by_id(i.user_id).user_name %></span>
<span class="c00 db f10"><%= i.created_at %></span>
</div>

</div>

<%= raw render(@items) %>

<% end %>
<%= paginate @items  %>
<% end %>

app/views/items/new.html.erb
<div class="block">
<h2><%= t(:add_item)%></h2>
<div class="block_content">

<%= form_for @item, :url => items_create_path, :html => {:multipart => true} do |f| %>

<%= errors_for(@item, t("error")).html_safe %>

<table>
<tbody>

<tr>
<td class="eformCln1 c00"><%= f.label t("item_name") %></td>
<td class="eformCln2"><%= f.text_field :item_name %></td>
</tr>

<tr>
<td class="eformCln1 c00"><%= f.label t("description") %></td>
<td class="eformCln2"><%= f.text_area :item_desc, :size => "60x12" %></td>
</tr>
<tr>
<td class="eformCln1 c00"> </td>
<td class="eformCln2"><%= collection_select :item, :category_id, Category.find(:all), :id, :category_name %>
<%= collection_select :item, :item_action_id, ItemAction.find(:all), :id, :item_act %></td>
</tr>

<% x=0 %>
<%= f.fields_for :item_photos do |builder|  %>
<tr>
<td class="eformCln1"> </td>
<td class="eformCln2">
    <div class="fm-item">
    <%= builder.file_field :photo,:id => "upload-file#{x}" %>
    </div>
    <div style="width: 50em;">
    <button type="submit" id="upload-button<%= x %>">Submit</button>
    <span id="file-name<%= x %>"></span>
    </div>
<% x+=1 %>
</td>
</tr>
<% end %>

<tr>
<td class="eformCln1"> </td>
<td class="eformCln2"><%= f.submit t(:add) %></td>
</tr>

</tbody>
</table>

<% end %>
</div>
</div>
<%= link_to t('back'), request.referer %>

app/views/items/show.html.erb
<div class="list_box">
<div class="list_box_left">

<div id="bigPic">
<% @item.item_photos.each do |pix| %>
<%= link_to(image_tag(pix.photo.url(:small)), pix.photo.url(:large), :rel => "lightbox") unless pix.photo.nil? %>
<% end %>
</div>

<% if @item.item_photos.count > 1 %>
<ul id="thumbs">
<% x = 1 %>
<% @item.item_photos.each do |pix| %>
<li rel="<%= x %>"><%= image_tag(pix.photo.url(:small)) %></li>
<% x += 1 %>
<% end %>
</ul>
<% end %>
</div>

<div class="list_box_right">

<%= render :partial => "admin_edit", :locals => { :item => @item } %>

<span class="db pb"><%= User.find_by_id(@item.user_id).city %></span>

<% if signed_in? %>
    <% if @item.user_id != current_user.id %>
	<% if current_user.basket_items.find_by_item_id(@item.id) %>
	    <span class="db pb fb cred"><%= t("in_basket")%></span>
	<% else %>
	    <span class="fr"><%= link_to "Хочу!", basket_add_path(@item.id),:class => "button c00" %></span>
	<% end %>
    <% end %>
<% end %>
</div>


<div class="list_box_middle">
<h3><%= @item.item_name %></h3>
<span class="db pb"><%= @item.item_desc %></span>
<span class="db"><%= image_tag "/assets/icons/user.png"%> <%= link_to @user.user_name, user_path(@user.id) %></span>
<span class="f10 c00 rp10"><%= image_tag "/assets/icons/cost.png"%> <%= @category.category_name %></span>
<span class="f10 c00"><%= image_tag "/assets/icons/bank.png"%> <%= @action.item_act %></span>
<span class="f10 db"><%= @item.created_at %></span>
</div>
</div>
<%= link_to t(:back), request.referer %>