config/routes.rb
Scarb::Application.routes.draw do

root :to => 'items#list'

match '/about' => 'application#about'

match 'basket/:id/add' => 'basket#add_item', :via=> [:get,:put], :as => :basket_add
match 'basket/:id/list' => 'basket#list', :via=> :get, :as => :basket_list
match 'basket/:id/delete' => 'basket#delete', :via=> :get, :as => :basket_delete

match 'inbox/:id/incoming' => 'inbox#incoming_list', :via=> :get, :as => :incoming_list
match 'inbox/:id/sent' => 'inbox#sent_list', :via=> :get, :as => :sent_list
match 'inbox/:id/notify' => 'inbox#notify_owner', :via=> :get, :as => :inbox_notify
match 'inbox/:id/reply' => 'inbox#reply', :via=> [:get,:post], :as => :inbox_reply
match 'inbox/:id/delete' => 'inbox#delete', :via=> :get, :as => :inbox_delete

match '/signup' => 'user#new'
match '/signin' => 'sessions#new', :via => [:get,:post], :as => :sessions_new
match '/signout' => 'sessions#destroy', :as => :sessions_out

match 'items' => 'items#list', :via=> :get, :as => :items_list
match 'items/create' => 'items#create', :via=> :post, :as => :items_create
match 'items/:id/update' => 'items#update', :via=> :put, :as => :items_update
match 'items/new' => 'items#new', :via=> [:get,:put], :as => :items_new
match 'items/:id' => 'items#show', :via=> :get, :as => :items
match 'items/:id/edit' => 'items#edit', :via=> [:get,:put], :as => :items_edit
match 'items/:id/delete' => 'items#delete', :via=> :get, :as => :items_delete

match 'user' => 'user#list', :via=> :get, :as => :user_list
match 'user/:id' => 'user#show', :via=> :get, :as => :user
match 'user/new' => 'user#new', :via=> :get, :as => :user_new
match 'user/create' => 'user#create', :via=> :post, :as => :user_create
match 'user/:id/edit' => 'user#edit', :via=> [:get,:put], :as => :user_edit
match 'user/:id/delete' => 'user#delete', :via=> :get, :as => :user_delete
match 'user/:id/items' => 'user#my_items', :via=> :get, :as => :user_items

get "user/update"

match 'category/:id' => 'category#show', :via=> :get, :as => :category
match 'category' => 'category#list', :via=> :get, :as => :category_list
 
  get "category/new"
 post "category/create"
  get "category/edit"
  get "category/update"
  get "category/delete"

end

app/views/layouts/_footer.html.erb
<div id="footer">
	<p>Copyright (c) 2012 Vavilen Tsiperovich. </p>
</div>
<%= debug(params) if Rails.env.development? %>

app/views/layouts/_latest.html.erb
<% items = latest_items %>
<% if items.blank? %>
<p>There are not any new items</p>
<% else %>
<% items.each do |i| %>

<div class="latest_list">
<div class="latest_list_l">
<%= link_to(image_tag(i.item_photos.first.photo.url(:small)),items_path(i.id)) unless i.item_photos.first.nil? %>
</div>
<div class ="latest_list_r">
<%= link_to i.item_name, items_path(:id=>i.id) %>
<span class="act01 db c00"><%= i.item_action.item_act %></span>
<span class="db c00 f10"><%= i.created_at.strftime("%d %b.") %></span>
</div>
</div>

<% end %>
<% end %>

app/views/layouts/_login.html.erb
<div id="login">
<%= render :template => '/sessions/new' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
 
  <%= stylesheet_link_tag 'main_style', :media => 'screen' %>
  <%= stylesheet_link_tag 'lightbox', :media => 'screen' %>
  <%= stylesheet_link_tag 'carousel', :media => 'screen' %>
  <%= stylesheet_link_tag 'jackedup', :media => 'screen' %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#"><span>Ska</span>rb  </a></h1>
				<p> Избавься от барахла! </p>
			</div>
			<div id="menu">
				<ul>
					<%= nav_link(t('home'),"application","about","http://xep.8800.org:4040/about").html_safe %>
					<%= nav_link(t('items'),"items","list",items_list_path).html_safe %>
					<%= nav_link(t('categories'),"category",nil,category_list_path).html_safe %>
					<% if is_admin? %>
					<%= nav_link(t('users'),"user",nil,user_list_path).html_safe %>
					<% end %>				
				</ul>
			</div>
		</div>
	</div>
<!-- end #header -->

<div id="page">
	<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
<% unless flash.blank? %> 
<div class="notify_box">
        <% flash.each do |key, value| %>
	<script type="text/javascript">humane.waitForMove = true; humane.log("<%= value %>")</script>
        <% end %>
</div>
<% end %>
						<div style="clear: both;">&nbsp;</div>
		<%= yield %>

					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
<% if current_user %>

<div id="sidemenu">
<h3>Привет <%= link_to current_user.user_name, current_user %></h3>
<% semantic_navigation :main, :html => { :class => 'primary' } do |n| %>
<% inbx_cnt = new_count %>
<% if !inbx_cnt.nil? && inbx_cnt > 0 %>
<div class="l_right"><%= inbx_cnt %></div>
<% end %>
<%= n.item t('my_inbox'), :html => {:id=> "my_inbox"} %>
<div class="submnu">
<%= n.item t('incoming'), :html => {:id=> "incoming"}, :link => incoming_list_path( :id => current_user.id), :disabled_if => proc { request.path == incoming_list_path(:id=>current_user.id) }%>
<%= n.item t('sent'), :html => {:id=> "sent"}, :link => sent_list_path( :id => current_user.id), :disabled_if => proc { request.path == sent_list_path(:id=>current_user.id) }%>
</div>

<% basket_cnt = inbasket_count %>
<% if !basket_cnt.nil? && basket_cnt > 0 %>
<div class="l_right"><%= basket_cnt %></div>
<% end %>
<%= n.item t('my_basket'), :html => {:id=> "my_basket"}, :link => basket_list_path( :id => current_user.id), :disabled_if => proc { request.path == basket_list_path(:id=>current_user.id) } %>
<%= n.item t('my_items'), :html => {:id=> "my_items"}, :link => user_items_path( :id => current_user.id), :disabled_if => proc { request.path == user_items_path(:id=>current_user.id) } %>
<%= n.item t('my_profile'), :html => {:id=> "my_profile"}, :link => user_path( :id => current_user.id), :disabled_if => proc { request.path == user_path(:id=>current_user.id) } %>
<%= n.item t('signout'), :html => {:id=> "sign_out"}, :link => sessions_out_path %>
<% end %>
</div>
    <% else %>
<%= render 'layouts/login' %>
<% end %>

<div id="sidebar">

<ul>
<div style="clear: both;">&nbsp;</div>
					
						<li>
							<h2><%= t("categories")%></h2>
							<ul>
							<% @categories = Category.find(:all) if @categories.nil? %>
							<% @categories.each do |c| %>
							<li><%= link_to c.category_name, items_list_path(:category => c.id) %></li>
							<% end %>
							</ul>
						</li>
					</ul>
				<h2><%= t("latest")%></h2>
				<%= render 'layouts/latest' %>

				</div>


				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
</div>

<%= render 'layouts/footer' %>

</body>
</html>